CREATE DATABASE IF NOT EXISTS db;
USE db;
CREATE TABLE IF NOT EXISTS test(
    id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT
);
ALTER TABLE test
    ADD COLUMN IF NOT EXISTS text TEXT DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS title TEXT DEFAULT NULL;
